server:
  port: 10101

logging:
  level:
    root: info

wx:
  appId: wx28572efe225803ee
  appSecret: 6d1ce29f6f123fhfz80c96a3face
  redirectUri: https://域名/receive
  invoice:
    spAppId: d3gyODU3MmZlZjIyNTgwM2VlXycPRuLgR86OKCmrScvyS0Xv0cjEhFm1P93b9uWpR7Df

